package dashteacup.pman;

/**
 * Exception used when the password file is improperly formatted and cannot be
 * parsed/interpreted.
 */
public class InvalidPasswordFileException extends Exception {

    /**
     * Construct a new {@link InvalidPasswordFileException} with null as the
     * detail message.
     */
    public InvalidPasswordFileException() {

    }

    /**
     * Construct a new {@link InvalidPasswordFileException} with the given detail
     * message.
     * @param message the detail message (accessed with {@link getMessage()}).
     */
    public InvalidPasswordFileException(String message) {
        super(message);
    }

    /**
     * Serialization marker generated by Eclipse.
     */
    private static final long serialVersionUID = -4795804557657075037L;

}
