package cs242.pcurry2.pm;

/**
 * Exception used when the user gives an invalid password to decrypt a file.
 */
public class BadPasswordException extends Exception {

    /**
     * Construct a {@link BadPasswordException} with the given detail message.
     * @param message the detail message (accessed with {@link getMessage()})
     */
    public BadPasswordException(String message) {
        super(message);
    }

    /**
     * Construct a new {@link BadPasswordException} will null as the detail message.
     */
    public BadPasswordException() {
    }

    /**
     * Serialization marker generated by Eclipse.
     */
    private static final long serialVersionUID = 7432200839234601313L;

}
